""" phase1_domain """
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = '0002_phase1_domain'
down_revision = '0001_bootstrap'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('builds',
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'id'),
    sa.UniqueConstraint('project_id', 'label')
    )
    op.create_index(op.f('ix_builds_project_id'), 'builds', ['project_id'], unique=False)
    op.create_table('categories',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'id'),
    sa.UniqueConstraint('project_id', 'slug')
    )
    op.create_index(op.f('ix_categories_project_id'), 'categories', ['project_id'], unique=False)
    op.create_table('locales',
    sa.Column('code', sa.String(length=63), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code'),
    sa.UniqueConstraint('project_id', 'id')
    )
    op.create_index(op.f('ix_locales_project_id'), 'locales', ['project_id'], unique=False)
    op.create_table('string_keys',
    sa.Column('string_id', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'id'),
    sa.UniqueConstraint('project_id', 'string_id')
    )
    op.create_index(op.f('ix_string_keys_project_id'), 'string_keys', ['project_id'], unique=False)
    op.create_table('situations',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'category_id'], ['categories.project_id', 'categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'category_id', 'id'),
    sa.UniqueConstraint('project_id', 'category_id', 'slug'),
    sa.UniqueConstraint('project_id', 'id')
    )
    op.create_index(op.f('ix_situations_project_id'), 'situations', ['project_id'], unique=False)
    op.create_table('string_entries',
    sa.Column('build_id', sa.UUID(), nullable=False),
    sa.Column('locale_id', sa.UUID(), nullable=False),
    sa.Column('string_key_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('char_length(text) <= 10000', name='ck_entry_text_length'),
    sa.ForeignKeyConstraint(['project_id', 'build_id'], ['builds.project_id', 'builds.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'locale_id'], ['locales.project_id', 'locales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'string_key_id'], ['string_keys.project_id', 'string_keys.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'build_id', 'string_key_id', 'locale_id')
    )
    op.create_index('ix_entries_catalog', 'string_entries', ['project_id', 'build_id', 'locale_id', 'string_key_id'], unique=False)
    op.create_index('ix_entries_key', 'string_entries', ['project_id', 'string_key_id'], unique=False)
    op.create_index('ix_entries_locale', 'string_entries', ['project_id', 'locale_id'], unique=False)
    op.create_index(op.f('ix_string_entries_project_id'), 'string_entries', ['project_id'], unique=False)
    op.create_table('screenshots',
    sa.Column('build_id', sa.UUID(), nullable=False),
    sa.Column('locale_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('situation_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('file_hash', sa.CHAR(length=64), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('metadata_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('client_upload_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("file_hash ~ '^[0-9a-f]{64}$'", name='ck_screenshot_hash'),
    sa.CheckConstraint("metadata_version = 1 AND jsonb_typeof(metadata) = 'object'", name='ck_screenshot_metadata'),
    sa.CheckConstraint("source = 'manual' AND client_upload_id IS NULL", name='ck_screenshot_phase1'),
    sa.CheckConstraint('size_bytes > 0 AND width > 0 AND height > 0', name='ck_screenshot_positive'),
    sa.ForeignKeyConstraint(['project_id', 'build_id'], ['builds.project_id', 'builds.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'category_id', 'situation_id'], ['situations.project_id', 'situations.category_id', 'situations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'locale_id'], ['locales.project_id', 'locales.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_screenshots_category', 'screenshots', ['project_id', 'category_id'], unique=False)
    op.create_index('ix_screenshots_filters', 'screenshots', ['project_id', 'build_id', 'locale_id', 'situation_id', sa.literal_column('uploaded_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_index('ix_screenshots_locale', 'screenshots', ['project_id', 'locale_id'], unique=False)
    op.create_index(op.f('ix_screenshots_project_id'), 'screenshots', ['project_id'], unique=False)
    op.create_index('ix_screenshots_recent', 'screenshots', ['project_id', sa.literal_column('uploaded_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_index('ix_screenshots_situation', 'screenshots', ['project_id', 'situation_id'], unique=False)
    op.create_table('situation_expected_strings',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('build_id', sa.UUID(), nullable=False),
    sa.Column('situation_id', sa.UUID(), nullable=False),
    sa.Column('string_key_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_expected_position'),
    sa.ForeignKeyConstraint(['project_id', 'build_id'], ['builds.project_id', 'builds.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'situation_id'], ['situations.project_id', 'situations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id', 'string_key_id'], ['string_keys.project_id', 'string_keys.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'build_id', 'situation_id', 'string_key_id'),
    sa.UniqueConstraint('project_id', 'build_id', 'situation_id', 'position')
    )
    op.create_index('ix_expected_key', 'situation_expected_strings', ['project_id', 'string_key_id'], unique=False)
    op.create_index('ix_expected_situation', 'situation_expected_strings', ['project_id', 'situation_id'], unique=False)
    op.create_index(op.f('ix_situation_expected_strings_project_id'), 'situation_expected_strings', ['project_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_situation_expected_strings_project_id'), table_name='situation_expected_strings')
    op.drop_index('ix_expected_situation', table_name='situation_expected_strings')
    op.drop_index('ix_expected_key', table_name='situation_expected_strings')
    op.drop_table('situation_expected_strings')
    op.drop_index('ix_screenshots_situation', table_name='screenshots')
    op.drop_index('ix_screenshots_recent', table_name='screenshots')
    op.drop_index(op.f('ix_screenshots_project_id'), table_name='screenshots')
    op.drop_index('ix_screenshots_locale', table_name='screenshots')
    op.drop_index('ix_screenshots_filters', table_name='screenshots')
    op.drop_index('ix_screenshots_category', table_name='screenshots')
    op.drop_table('screenshots')
    op.drop_index(op.f('ix_string_entries_project_id'), table_name='string_entries')
    op.drop_index('ix_entries_locale', table_name='string_entries')
    op.drop_index('ix_entries_key', table_name='string_entries')
    op.drop_index('ix_entries_catalog', table_name='string_entries')
    op.drop_table('string_entries')
    op.drop_index(op.f('ix_situations_project_id'), table_name='situations')
    op.drop_table('situations')
    op.drop_index(op.f('ix_string_keys_project_id'), table_name='string_keys')
    op.drop_table('string_keys')
    op.drop_index(op.f('ix_locales_project_id'), table_name='locales')
    op.drop_table('locales')
    op.drop_index(op.f('ix_categories_project_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_builds_project_id'), table_name='builds')
    op.drop_table('builds')
    op.drop_table('projects')
    # ### end Alembic commands ###
